---
- name: Backup Configs
  hosts: home_lab_all
  gather_facts: false
  connection: network_cli
  
  tasks:
  
    - name: backup ios config
      ios_config:
        backup: yes
        backup_options:
          filename: "running-config.config"
          dir_path: "/data/{{ inventory_hostname }}"
