---
- name: Backup Configs
  hosts: 10.20.20.145
  gather_facts: false
  connection: network_cli
  
  tasks:
  
    - name: backup ios config
      ios_config:
        backup: yes
        backup_options:
          filename: "running-config.config"
          dir_path: "/data/{{ inventory_hostname }}"
